
    create table activity_like (
        id integer generated by default as identity,
        member_id integer not null,
        vendor_activity_id integer not null,
        primary key (id)
    );

    create table activity_people_number (
        current_participants integer not null,
        id integer generated by default as identity,
        max_participants integer not null,
        vendor_activity_id integer not null unique,
        primary key (id)
    );

    create table activity_registration (
        id integer generated by default as identity,
        member_id integer not null,
        vendor_activity_id integer not null,
        registration_time timestamp(6) not null,
        status varchar(255) not null,
        primary key (id)
    );

    create table activity_type (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table admin (
        id integer not null,
        registration_date timestamp(6),
        name varchar(255) not null,
        role enum ('ADMIN','EMPLOYEE','SA') not null,
        primary key (id)
    );

    create table admin_product_reply (
        admin_id integer not null,
        id integer generated by default as identity,
        product_review_id integer not null,
        reply_time timestamp(6) not null,
        reply_text varchar(255) not null,
        primary key (id)
    );

    create table calendar_event (
        id integer generated by default as identity,
        vendor_activity_id integer not null,
        vendor_id integer not null,
        created_at timestamp(6),
        end_time timestamp(6) not null,
        start_time timestamp(6) not null,
        updated_at timestamp(6),
        color varchar(255),
        event_title varchar(255) not null,
        primary key (id)
    );

    create table cart (
        id integer generated by default as identity,
        member_id integer,
        product_id integer not null,
        quantity integer not null,
        created_date timestamp(6),
        primary key (id)
    );

    create table certification_tag (
        id integer generated by default as identity,
        keywords varchar(255),
        tag_name varchar(255) not null unique,
        primary key (id)
    );

    create table chat_messages (
        id integer generated by default as identity,
        isRead boolean not null,
        receiver_id integer not null,
        sender_id integer not null,
        send_time timestamp(6),
        content varchar(255) not null,
        primary key (id)
    );

    create table chat_photo (
        chat_messages_id integer not null,
        id integer generated by default as identity,
        photo varchar(255),
        primary key (id)
    );

    create table coupons (
        discount_type boolean not null,
        discount_value numeric(10,0) not null,
        id integer generated by default as identity,
        limit_count integer not null,
        min_order_value numeric(10,0) not null,
        status bit default 0 not null,
        valid_end timestamp(6) not null,
        valid_start timestamp(6) not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table friendly_shop (
        id integer generated by default as identity,
        latitude numeric(38,2),
        longitude numeric(38,2),
        vendor_category_id integer,
        vendor_id integer,
        address varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table member (
        birthdate date,
        gender boolean not null,
        id integer not null,
        status BIT DEFAULT 0 not null,
        updated_date timestamp(6),
        address varchar(255),
        name varchar(255),
        phone varchar(255),
        profile_photo blob,
        primary key (id)
    );

    create table member_coupon (
        coupons_id integer not null,
        member_id integer not null,
        status bit default 1,
        usage_count integer,
        primary key (coupons_id, member_id)
    );

    create table notification (
        id integer generated by default as identity,
        is_read boolean not null,
        member_id integer,
        vendor_activity_id integer,
        vendor_id integer,
        sent_time timestamp(6) not null,
        notification_content varchar(1000) not null,
        notification_title varchar(255) not null,
        primary key (id)
    );

    create table "order" (
        coupon_id integer,
        discount_amount numeric(10,0) not null,
        id integer generated by default as identity,
        member_id integer not null,
        order_status_id integer not null,
        shipping_fee numeric(10,0) not null,
        subtotal numeric(10,0) not null,
        total_amount numeric(10,0) not null,
        created_time timestamp(6) not null,
        updated_date timestamp(6),
        note varchar(255),
        primary key (id)
    );

    create table order_details (
        discount_price numeric(10,0),
        id integer generated by default as identity,
        order_id integer not null,
        product_id integer not null,
        quantity integer not null,
        total_price numeric(10,0) not null,
        unit_price numeric(10,0) not null,
        primary key (id)
    );

    create table order_status (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table payment (
        id integer generated by default as identity,
        order_id integer not null unique,
        payment_amount numeric(10,0) not null,
        payment_category_id integer not null,
        payment_status_id integer not null,
        payment_date timestamp(6) not null,
        updated_date timestamp(6) not null,
        trade_no varchar(255),
        primary key (id)
    );

    create table payment_category (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table payment_status (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product (
        discount_price numeric(10,0),
        id integer generated by default as identity,
        product_color_id integer,
        product_detail_id integer not null,
        product_size_id integer,
        status boolean not null,
        stock_quantity integer not null,
        unit_price numeric(10,0) not null,
        created_time timestamp(6),
        photo varbinary(255),
        primary key (id),
        unique (product_detail_id, product_color_id, product_size_id)
    );

    create table product_category (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_color (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_detail (
        id integer generated by default as identity,
        product_category_id integer not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_review (
        id integer generated by default as identity,
        member_id integer not null,
        product_id integer not null,
        rating integer not null,
        review_time timestamp(6),
        review_description varchar(255),
        primary key (id),
        unique (product_id, member_id)
    );

    create table product_review_photo (
        id integer generated by default as identity,
        product_review_id integer not null,
        review_photo varbinary(255) not null,
        primary key (id)
    );

    create table product_size (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table review_photo (
        id integer generated by default as identity,
        vendor_review_id integer not null,
        photo blob not null,
        primary key (id)
    );

    create table shipping (
        id integer generated by default as identity,
        order_id integer not null unique,
        shipping_address_id integer not null,
        shipping_category_id integer not null,
        shipping_date timestamp(6) not null,
        updated_time timestamp(6) not null,
        receiver_name varchar(255) not null,
        receiver_phone varchar(255) not null,
        primary key (id)
    );

    create table shipping_address (
        id integer generated by default as identity,
        is_current BIT DEFAULT 0 not null,
        member_id integer not null,
        city varchar(255) not null,
        street varchar(255) not null,
        primary key (id)
    );

    create table shipping_category (
        id integer generated by default as identity,
        shipping_cost DECIMAL(10,0) DEFAULT 0 not null,
        shipping_day INT DEFAULT 7 not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        admin_level integer check ((admin_level<=1) and (admin_level>=0)),
        email_verified boolean,
        id integer generated by default as identity,
        is_super_admin boolean,
        local_enabled boolean,
        token_expiry timestamp(6),
        email varchar(255) not null,
        password varchar(255) not null,
        verification_token varchar(255),
        provider enum ('GOOGLE','LOCAL'),
        user_role enum ('ADMIN','MEMBER','VENDOR') not null,
        primary key (id)
    );

    create table vendor (
        avg_rating_environment float(24),
        avg_rating_price float(24),
        avg_rating_service float(24),
        event_count integer,
        id integer not null,
        review_count integer,
        status boolean not null,
        total_rating float(24),
        vendor_category_id integer,
        registration_date timestamp(6),
        updated_date timestamp(6),
        address varchar(255),
        contact_email varchar(255),
        contact_person varchar(255),
        description varchar(255),
        logo_img varbinary(255),
        name varchar(255),
        phone varchar(255),
        taxid_number varchar(255),
        vendor_level varchar(255) not null,
        primary key (id)
    );

    create table vendor_activity (
        activity_type_id integer not null,
        id integer generated by default as identity,
        is_registration_required boolean not null,
        number_visitor integer not null,
        vendor_id integer not null,
        end_time timestamp(6) not null,
        registration_date timestamp(6),
        start_time timestamp(6) not null,
        address varchar(255) not null,
        description varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table vendor_activity_images (
        id integer generated by default as identity,
        vendor_activity_id integer not null,
        image blob not null,
        primary key (id)
    );

    create table vendor_activity_review (
        id integer generated by default as identity,
        member_id integer,
        vendor_activity_id integer not null,
        vendor_id integer not null,
        review_time timestamp(6) not null,
        review_content varchar(255) not null,
        primary key (id)
    );

    create table vendor_category (
        id integer generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table vendor_certification (
        id integer generated by default as identity,
        vendor_id integer not null,
        approved_date timestamp(6),
        request_date timestamp(6),
        reason varchar(1000),
        certification_status NVARCHAR(50) DEFAULT '申請中' not null,
        primary key (id)
    );

    create table vendor_certification_tag (
        certification_id integer not null,
        id integer generated by default as identity,
        meets_standard boolean not null,
        tag_id integer not null,
        vendor_id integer not null,
        primary key (id)
    );

    create table vendor_images (
        id integer generated by default as identity,
        vendor_id integer not null,
        image blob not null,
        primary key (id)
    );

    create table vendor_like (
        id integer generated by default as identity,
        member_id integer,
        vendor_id integer,
        primary key (id)
    );

    create table vendor_review (
        id integer generated by default as identity,
        member_id integer not null,
        rating_environment integer,
        rating_price integer,
        rating_service integer,
        vendor_id integer not null,
        review_time timestamp(6) not null,
        review_content varchar(255),
        primary key (id)
    );

    alter table if exists activity_like 
       add constraint FKpqm80ijk7i1sq98rl7hyb30e3 
       foreign key (member_id) 
       references member;

    alter table if exists activity_like 
       add constraint FKkljpm2l7e6fvac0741v1p3x3f 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists activity_people_number 
       add constraint FKdh7cllsfed811p7wrohr7fxu3 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists activity_registration 
       add constraint FKl0150txbqukiomt4jo9bhq3lt 
       foreign key (member_id) 
       references member;

    alter table if exists activity_registration 
       add constraint FK4peep8xww1qx98bkiotep4mdf 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists admin 
       add constraint FKqer4e53tfnl17s22ior7fcsv8 
       foreign key (id) 
       references users;

    alter table if exists admin_product_reply 
       add constraint FK6h7i4cuq6asgpsteiaxi7p4fr 
       foreign key (admin_id) 
       references admin;

    alter table if exists admin_product_reply 
       add constraint FKfyxyc2vxmps1i7by5dfybut51 
       foreign key (product_review_id) 
       references product_review;

    alter table if exists calendar_event 
       add constraint FKsptdbodpdgjbat34pucrxc20b 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists calendar_event 
       add constraint FK78smuqnpgj00uujvognmjirwq 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists cart 
       add constraint FKix170nytunweovf2v9137mx2o 
       foreign key (member_id) 
       references member;

    alter table if exists cart 
       add constraint FK3d704slv66tw6x5hmbm6p2x3u 
       foreign key (product_id) 
       references product;

    alter table if exists chat_messages 
       add constraint FKand7mh9iu4kt3n1tn2w9i9of0 
       foreign key (receiver_id) 
       references users;

    alter table if exists chat_messages 
       add constraint FKgiqeap8ays4lf684x7m0r2729 
       foreign key (sender_id) 
       references users;

    alter table if exists chat_photo 
       add constraint FK6pu22838suxmuaeqcpplhyh0q 
       foreign key (chat_messages_id) 
       references chat_messages;

    alter table if exists friendly_shop 
       add constraint FK8q79tp71ewdt7trb3v2hsxjnv 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists friendly_shop 
       add constraint FK86a55ixovh0q2hgnkgrpjo8t 
       foreign key (vendor_category_id) 
       references vendor_category;

    alter table if exists member 
       add constraint FKeog0m8jm2ck5j048aeswwrqcv 
       foreign key (id) 
       references users;

    alter table if exists member_coupon 
       add constraint FK56chduq1uvumvj9xv6by7jqrl 
       foreign key (coupons_id) 
       references coupons;

    alter table if exists member_coupon 
       add constraint FKf8n3lu0dfwmhvcikamg220lgg 
       foreign key (member_id) 
       references member;

    alter table if exists notification 
       add constraint FK1xep8o2ge7if6diclyyx53v4q 
       foreign key (member_id) 
       references member;

    alter table if exists notification 
       add constraint FK7usgy1efav68q2dfbjnf7a870 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists notification 
       add constraint FKhfr2sgrl6fhi36elb94vqedft 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists "order" 
       add constraint FKt2l0f3ogjf20tq58glk8t09tr 
       foreign key (coupon_id) 
       references coupons;

    alter table if exists "order" 
       add constraint FKbtfnkke0l8kyq7lyhpwjtg5ev 
       foreign key (member_id) 
       references member;

    alter table if exists "order" 
       add constraint FKcxpcc11kb45j9kjf2qol0pmvm 
       foreign key (order_status_id) 
       references order_status;

    alter table if exists order_details 
       add constraint FK4du41awqfrviisty6wc7caunp 
       foreign key (order_id) 
       references "order";

    alter table if exists order_details 
       add constraint FKinivj2k1370kw224lavkm3rqm 
       foreign key (product_id) 
       references product;

    alter table if exists payment 
       add constraint FK33pd2iqamm9gp5c14r1catra2 
       foreign key (order_id) 
       references "order";

    alter table if exists payment 
       add constraint FKd9y272nk5a74rdtxawxdmqpds 
       foreign key (payment_category_id) 
       references payment_category;

    alter table if exists payment 
       add constraint FKkggljyawkbwc50f0fentflj8t 
       foreign key (payment_status_id) 
       references payment_status;

    alter table if exists product 
       add constraint FKrc2n9xqgygbx2300ka9x1mseb 
       foreign key (product_color_id) 
       references product_color;

    alter table if exists product 
       add constraint FKr9faxumx2401v6n081g0ju9u 
       foreign key (product_detail_id) 
       references product_detail;

    alter table if exists product 
       add constraint FK28qnlp6clpagwv0fqjnqqbtid 
       foreign key (product_size_id) 
       references product_size;

    alter table if exists product_detail 
       add constraint FK27il54tvxjeg6v2wloaobkpv1 
       foreign key (product_category_id) 
       references product_category;

    alter table if exists product_review 
       add constraint FKrgdi6011r51iv9nf26omocl7v 
       foreign key (member_id) 
       references member;

    alter table if exists product_review 
       add constraint FKkaqmhakwt05p3n0px81b9pdya 
       foreign key (product_id) 
       references product;

    alter table if exists product_review_photo 
       add constraint FK8kmfeghxxyk9oomh9y72a7p8k 
       foreign key (product_review_id) 
       references product_review;

    alter table if exists review_photo 
       add constraint FK686r5hsoi21jjgw1ta0ffppwr 
       foreign key (vendor_review_id) 
       references vendor_review;

    alter table if exists shipping 
       add constraint FK1tuspk6hsudt3desli2ty4609 
       foreign key (order_id) 
       references "order";

    alter table if exists shipping 
       add constraint FKjdy5t5asbskyrojgw19vps94q 
       foreign key (shipping_address_id) 
       references shipping_address;

    alter table if exists shipping 
       add constraint FK2y9087ci7maahookairsbkd92 
       foreign key (shipping_category_id) 
       references shipping_category;

    alter table if exists shipping_address 
       add constraint FKmyfu4e8no9xiafndjxjmu8177 
       foreign key (member_id) 
       references member;

    alter table if exists vendor 
       add constraint FKf7029qgg0bcjtf6dbc72embqr 
       foreign key (vendor_category_id) 
       references vendor_category;

    alter table if exists vendor 
       add constraint FK23he99nciwspxtldcr1x7djjk 
       foreign key (id) 
       references users;

    alter table if exists vendor_activity 
       add constraint FKanfvmjq668u9w5of7i4laextn 
       foreign key (activity_type_id) 
       references activity_type;

    alter table if exists vendor_activity 
       add constraint FKlypd3wp8blaqn5vjk2aq06ocf 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_activity_images 
       add constraint FKmq3djj5ygwhtms4805cqbpoqa 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists vendor_activity_review 
       add constraint FK24sn9uaej1vicb1qsll87qsnh 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_activity_review 
       add constraint FKgrykb4d828786x8bwmfe6hofb 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists vendor_certification 
       add constraint FKi7k9wkl7kwycsd1yt4s3uiwvf 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_certification_tag 
       add constraint FKc6o7lxsxelxibd84cct8md7cs 
       foreign key (certification_id) 
       references vendor_certification;

    alter table if exists vendor_certification_tag 
       add constraint FKhwi9r3hvaprsof91bn0rv4k3m 
       foreign key (tag_id) 
       references certification_tag;

    alter table if exists vendor_certification_tag 
       add constraint FKqxdsuf5fnn8qr42r8quee527r 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_images 
       add constraint FKgyn512l9xa4ejyq2vomlj2r7s 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_review 
       add constraint FKmlrsk9erd14566a6kufo343l 
       foreign key (member_id) 
       references member;

    alter table if exists vendor_review 
       add constraint FK6gv7f3skkj0ew5xsrq8sj47hy 
       foreign key (vendor_id) 
       references vendor;

    create table activity_like (
        id integer generated by default as identity,
        member_id integer not null,
        vendor_activity_id integer not null,
        primary key (id)
    );

    create table activity_people_number (
        current_participants integer not null,
        id integer generated by default as identity,
        max_participants integer not null,
        vendor_activity_id integer not null unique,
        primary key (id)
    );

    create table activity_registration (
        id integer generated by default as identity,
        member_id integer not null,
        vendor_activity_id integer not null,
        registration_time timestamp(6) not null,
        status varchar(255) not null,
        primary key (id)
    );

    create table activity_type (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table admin (
        id integer not null,
        registration_date timestamp(6),
        name varchar(255) not null,
        role enum ('ADMIN','EMPLOYEE','SA') not null,
        primary key (id)
    );

    create table admin_product_reply (
        admin_id integer not null,
        id integer generated by default as identity,
        product_review_id integer not null,
        reply_time timestamp(6) not null,
        reply_text varchar(255) not null,
        primary key (id)
    );

    create table calendar_event (
        id integer generated by default as identity,
        vendor_activity_id integer not null,
        vendor_id integer not null,
        created_at timestamp(6),
        end_time timestamp(6) not null,
        start_time timestamp(6) not null,
        updated_at timestamp(6),
        color varchar(255),
        event_title varchar(255) not null,
        primary key (id)
    );

    create table cart (
        id integer generated by default as identity,
        member_id integer,
        product_id integer not null,
        quantity integer not null,
        created_date timestamp(6),
        primary key (id)
    );

    create table certification_tag (
        id integer generated by default as identity,
        keywords varchar(255),
        tag_name varchar(255) not null unique,
        primary key (id)
    );

    create table chat_messages (
        id integer generated by default as identity,
        isRead boolean not null,
        receiver_id integer not null,
        sender_id integer not null,
        send_time timestamp(6),
        content varchar(255) not null,
        primary key (id)
    );

    create table chat_photo (
        chat_messages_id integer not null,
        id integer generated by default as identity,
        photo varchar(255),
        primary key (id)
    );

    create table coupons (
        discount_type boolean not null,
        discount_value numeric(10,0) not null,
        id integer generated by default as identity,
        limit_count integer not null,
        min_order_value numeric(10,0) not null,
        status bit default 0 not null,
        valid_end timestamp(6) not null,
        valid_start timestamp(6) not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table friendly_shop (
        id integer generated by default as identity,
        latitude numeric(38,2),
        longitude numeric(38,2),
        vendor_category_id integer,
        vendor_id integer,
        address varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table member (
        birthdate date,
        gender boolean not null,
        id integer not null,
        status BIT DEFAULT 0 not null,
        updated_date timestamp(6),
        address varchar(255),
        name varchar(255),
        phone varchar(255),
        profile_photo blob,
        primary key (id)
    );

    create table member_coupon (
        coupons_id integer not null,
        member_id integer not null,
        status bit default 1,
        usage_count integer,
        primary key (coupons_id, member_id)
    );

    create table notification (
        id integer generated by default as identity,
        is_read boolean not null,
        member_id integer,
        vendor_activity_id integer,
        vendor_id integer,
        sent_time timestamp(6) not null,
        notification_content varchar(1000) not null,
        notification_title varchar(255) not null,
        primary key (id)
    );

    create table "order" (
        coupon_id integer,
        discount_amount numeric(10,0) not null,
        id integer generated by default as identity,
        member_id integer not null,
        order_status_id integer not null,
        shipping_fee numeric(10,0) not null,
        subtotal numeric(10,0) not null,
        total_amount numeric(10,0) not null,
        created_time timestamp(6) not null,
        updated_date timestamp(6),
        note varchar(255),
        primary key (id)
    );

    create table order_details (
        discount_price numeric(10,0),
        id integer generated by default as identity,
        order_id integer not null,
        product_id integer not null,
        quantity integer not null,
        total_price numeric(10,0) not null,
        unit_price numeric(10,0) not null,
        primary key (id)
    );

    create table order_status (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table payment (
        id integer generated by default as identity,
        order_id integer not null unique,
        payment_amount numeric(10,0) not null,
        payment_category_id integer not null,
        payment_status_id integer not null,
        payment_date timestamp(6) not null,
        updated_date timestamp(6) not null,
        trade_no varchar(255),
        primary key (id)
    );

    create table payment_category (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table payment_status (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product (
        discount_price numeric(10,0),
        id integer generated by default as identity,
        product_color_id integer,
        product_detail_id integer not null,
        product_size_id integer,
        status boolean not null,
        stock_quantity integer not null,
        unit_price numeric(10,0) not null,
        created_time timestamp(6),
        photo blob,
        primary key (id),
        unique (product_detail_id, product_color_id, product_size_id)
    );

    create table product_category (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_color (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_detail (
        id integer generated by default as identity,
        product_category_id integer not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_review (
        id integer generated by default as identity,
        member_id integer not null,
        product_id integer not null,
        rating integer not null,
        review_time timestamp(6),
        review_description varchar(255),
        primary key (id),
        unique (product_id, member_id)
    );

    create table product_review_photo (
        id integer generated by default as identity,
        product_review_id integer not null,
        review_photo blob not null,
        primary key (id)
    );

    create table product_size (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table review_photo (
        id integer generated by default as identity,
        vendor_review_id integer not null,
        photo blob not null,
        primary key (id)
    );

    create table shipping (
        id integer generated by default as identity,
        order_id integer not null unique,
        shipping_address_id integer not null,
        shipping_category_id integer not null,
        shipping_date timestamp(6) not null,
        updated_time timestamp(6) not null,
        receiver_name varchar(255) not null,
        receiver_phone varchar(255) not null,
        primary key (id)
    );

    create table shipping_address (
        id integer generated by default as identity,
        is_current BIT DEFAULT 0 not null,
        member_id integer not null,
        city varchar(255) not null,
        street varchar(255) not null,
        primary key (id)
    );

    create table shipping_category (
        id integer generated by default as identity,
        shipping_cost DECIMAL(10,0) DEFAULT 0 not null,
        shipping_day INT DEFAULT 7 not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        admin_level integer check ((admin_level<=1) and (admin_level>=0)),
        email_verified boolean,
        id integer generated by default as identity,
        is_super_admin boolean,
        local_enabled boolean,
        token_expiry timestamp(6),
        email varchar(255) not null,
        password varchar(255) not null,
        verification_token varchar(255),
        provider enum ('GOOGLE','LOCAL'),
        user_role enum ('ADMIN','MEMBER','VENDOR') not null,
        primary key (id)
    );

    create table vendor (
        avg_rating_environment float(24),
        avg_rating_price float(24),
        avg_rating_service float(24),
        event_count integer,
        id integer not null,
        review_count integer,
        status boolean not null,
        total_rating float(24),
        vendor_category_id integer,
        registration_date timestamp(6),
        updated_date timestamp(6),
        address varchar(255),
        contact_email varchar(255),
        contact_person varchar(255),
        description varchar(255),
        logo_img varbinary(255),
        name varchar(255),
        phone varchar(255),
        taxid_number varchar(255),
        vendor_level varchar(255) not null,
        primary key (id)
    );

    create table vendor_activity (
        activity_type_id integer not null,
        id integer generated by default as identity,
        is_registration_required boolean not null,
        number_visitor integer not null,
        vendor_id integer not null,
        end_time timestamp(6) not null,
        registration_date timestamp(6),
        start_time timestamp(6) not null,
        address varchar(255) not null,
        description varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table vendor_activity_images (
        id integer generated by default as identity,
        vendor_activity_id integer not null,
        image blob not null,
        primary key (id)
    );

    create table vendor_activity_review (
        id integer generated by default as identity,
        member_id integer,
        vendor_activity_id integer not null,
        vendor_id integer not null,
        review_time timestamp(6) not null,
        review_content varchar(255) not null,
        primary key (id)
    );

    create table vendor_category (
        id integer generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table vendor_certification (
        id integer generated by default as identity,
        vendor_id integer not null,
        approved_date timestamp(6),
        request_date timestamp(6),
        reason varchar(1000),
        certification_status NVARCHAR(50) DEFAULT '申請中' not null,
        primary key (id)
    );

    create table vendor_certification_tag (
        certification_id integer not null,
        id integer generated by default as identity,
        meets_standard boolean not null,
        tag_id integer not null,
        vendor_id integer not null,
        primary key (id)
    );

    create table vendor_images (
        id integer generated by default as identity,
        vendor_id integer not null,
        image blob not null,
        primary key (id)
    );

    create table vendor_like (
        id integer generated by default as identity,
        member_id integer,
        vendor_id integer,
        primary key (id)
    );

    create table vendor_review (
        id integer generated by default as identity,
        member_id integer not null,
        rating_environment integer,
        rating_price integer,
        rating_service integer,
        vendor_id integer not null,
        review_time timestamp(6) not null,
        review_content varchar(255),
        primary key (id)
    );

    alter table if exists activity_like 
       add constraint FKpqm80ijk7i1sq98rl7hyb30e3 
       foreign key (member_id) 
       references member;

    alter table if exists activity_like 
       add constraint FKkljpm2l7e6fvac0741v1p3x3f 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists activity_people_number 
       add constraint FKdh7cllsfed811p7wrohr7fxu3 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists activity_registration 
       add constraint FKl0150txbqukiomt4jo9bhq3lt 
       foreign key (member_id) 
       references member;

    alter table if exists activity_registration 
       add constraint FK4peep8xww1qx98bkiotep4mdf 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists admin 
       add constraint FKqer4e53tfnl17s22ior7fcsv8 
       foreign key (id) 
       references users;

    alter table if exists admin_product_reply 
       add constraint FK6h7i4cuq6asgpsteiaxi7p4fr 
       foreign key (admin_id) 
       references admin;

    alter table if exists admin_product_reply 
       add constraint FKfyxyc2vxmps1i7by5dfybut51 
       foreign key (product_review_id) 
       references product_review;

    alter table if exists calendar_event 
       add constraint FKsptdbodpdgjbat34pucrxc20b 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists calendar_event 
       add constraint FK78smuqnpgj00uujvognmjirwq 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists cart 
       add constraint FKix170nytunweovf2v9137mx2o 
       foreign key (member_id) 
       references member;

    alter table if exists cart 
       add constraint FK3d704slv66tw6x5hmbm6p2x3u 
       foreign key (product_id) 
       references product;

    alter table if exists chat_messages 
       add constraint FKand7mh9iu4kt3n1tn2w9i9of0 
       foreign key (receiver_id) 
       references users;

    alter table if exists chat_messages 
       add constraint FKgiqeap8ays4lf684x7m0r2729 
       foreign key (sender_id) 
       references users;

    alter table if exists chat_photo 
       add constraint FK6pu22838suxmuaeqcpplhyh0q 
       foreign key (chat_messages_id) 
       references chat_messages;

    alter table if exists friendly_shop 
       add constraint FK8q79tp71ewdt7trb3v2hsxjnv 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists friendly_shop 
       add constraint FK86a55ixovh0q2hgnkgrpjo8t 
       foreign key (vendor_category_id) 
       references vendor_category;

    alter table if exists member 
       add constraint FKeog0m8jm2ck5j048aeswwrqcv 
       foreign key (id) 
       references users;

    alter table if exists member_coupon 
       add constraint FK56chduq1uvumvj9xv6by7jqrl 
       foreign key (coupons_id) 
       references coupons;

    alter table if exists member_coupon 
       add constraint FKf8n3lu0dfwmhvcikamg220lgg 
       foreign key (member_id) 
       references member;

    alter table if exists notification 
       add constraint FK1xep8o2ge7if6diclyyx53v4q 
       foreign key (member_id) 
       references member;

    alter table if exists notification 
       add constraint FK7usgy1efav68q2dfbjnf7a870 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists notification 
       add constraint FKhfr2sgrl6fhi36elb94vqedft 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists "order" 
       add constraint FKt2l0f3ogjf20tq58glk8t09tr 
       foreign key (coupon_id) 
       references coupons;

    alter table if exists "order" 
       add constraint FKbtfnkke0l8kyq7lyhpwjtg5ev 
       foreign key (member_id) 
       references member;

    alter table if exists "order" 
       add constraint FKcxpcc11kb45j9kjf2qol0pmvm 
       foreign key (order_status_id) 
       references order_status;

    alter table if exists order_details 
       add constraint FK4du41awqfrviisty6wc7caunp 
       foreign key (order_id) 
       references "order";

    alter table if exists order_details 
       add constraint FKinivj2k1370kw224lavkm3rqm 
       foreign key (product_id) 
       references product;

    alter table if exists payment 
       add constraint FK33pd2iqamm9gp5c14r1catra2 
       foreign key (order_id) 
       references "order";

    alter table if exists payment 
       add constraint FKd9y272nk5a74rdtxawxdmqpds 
       foreign key (payment_category_id) 
       references payment_category;

    alter table if exists payment 
       add constraint FKkggljyawkbwc50f0fentflj8t 
       foreign key (payment_status_id) 
       references payment_status;

    alter table if exists product 
       add constraint FKrc2n9xqgygbx2300ka9x1mseb 
       foreign key (product_color_id) 
       references product_color;

    alter table if exists product 
       add constraint FKr9faxumx2401v6n081g0ju9u 
       foreign key (product_detail_id) 
       references product_detail;

    alter table if exists product 
       add constraint FK28qnlp6clpagwv0fqjnqqbtid 
       foreign key (product_size_id) 
       references product_size;

    alter table if exists product_detail 
       add constraint FK27il54tvxjeg6v2wloaobkpv1 
       foreign key (product_category_id) 
       references product_category;

    alter table if exists product_review 
       add constraint FKrgdi6011r51iv9nf26omocl7v 
       foreign key (member_id) 
       references member;

    alter table if exists product_review 
       add constraint FKkaqmhakwt05p3n0px81b9pdya 
       foreign key (product_id) 
       references product;

    alter table if exists product_review_photo 
       add constraint FK8kmfeghxxyk9oomh9y72a7p8k 
       foreign key (product_review_id) 
       references product_review;

    alter table if exists review_photo 
       add constraint FK686r5hsoi21jjgw1ta0ffppwr 
       foreign key (vendor_review_id) 
       references vendor_review;

    alter table if exists shipping 
       add constraint FK1tuspk6hsudt3desli2ty4609 
       foreign key (order_id) 
       references "order";

    alter table if exists shipping 
       add constraint FKjdy5t5asbskyrojgw19vps94q 
       foreign key (shipping_address_id) 
       references shipping_address;

    alter table if exists shipping 
       add constraint FK2y9087ci7maahookairsbkd92 
       foreign key (shipping_category_id) 
       references shipping_category;

    alter table if exists shipping_address 
       add constraint FKmyfu4e8no9xiafndjxjmu8177 
       foreign key (member_id) 
       references member;

    alter table if exists vendor 
       add constraint FKf7029qgg0bcjtf6dbc72embqr 
       foreign key (vendor_category_id) 
       references vendor_category;

    alter table if exists vendor 
       add constraint FK23he99nciwspxtldcr1x7djjk 
       foreign key (id) 
       references users;

    alter table if exists vendor_activity 
       add constraint FKanfvmjq668u9w5of7i4laextn 
       foreign key (activity_type_id) 
       references activity_type;

    alter table if exists vendor_activity 
       add constraint FKlypd3wp8blaqn5vjk2aq06ocf 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_activity_images 
       add constraint FKmq3djj5ygwhtms4805cqbpoqa 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists vendor_activity_review 
       add constraint FK24sn9uaej1vicb1qsll87qsnh 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_activity_review 
       add constraint FKgrykb4d828786x8bwmfe6hofb 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists vendor_certification 
       add constraint FKi7k9wkl7kwycsd1yt4s3uiwvf 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_certification_tag 
       add constraint FKc6o7lxsxelxibd84cct8md7cs 
       foreign key (certification_id) 
       references vendor_certification;

    alter table if exists vendor_certification_tag 
       add constraint FKhwi9r3hvaprsof91bn0rv4k3m 
       foreign key (tag_id) 
       references certification_tag;

    alter table if exists vendor_certification_tag 
       add constraint FKqxdsuf5fnn8qr42r8quee527r 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_images 
       add constraint FKgyn512l9xa4ejyq2vomlj2r7s 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_review 
       add constraint FKmlrsk9erd14566a6kufo343l 
       foreign key (member_id) 
       references member;

    alter table if exists vendor_review 
       add constraint FK6gv7f3skkj0ew5xsrq8sj47hy 
       foreign key (vendor_id) 
       references vendor;

    create table activity_like (
        id integer generated by default as identity,
        member_id integer not null,
        vendor_activity_id integer not null,
        primary key (id)
    );

    create table activity_people_number (
        current_participants integer not null,
        id integer generated by default as identity,
        max_participants integer not null,
        vendor_activity_id integer not null unique,
        primary key (id)
    );

    create table activity_registration (
        id integer generated by default as identity,
        member_id integer not null,
        vendor_activity_id integer not null,
        registration_time timestamp(6) not null,
        status varchar(255) not null,
        primary key (id)
    );

    create table activity_type (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table admin (
        id integer not null,
        registration_date timestamp(6),
        name varchar(255) not null,
        role enum ('ADMIN','EMPLOYEE','SA') not null,
        primary key (id)
    );

    create table admin_product_reply (
        admin_id integer not null,
        id integer generated by default as identity,
        product_review_id integer not null,
        reply_time timestamp(6) not null,
        reply_text varchar(255) not null,
        primary key (id)
    );

    create table calendar_event (
        id integer generated by default as identity,
        vendor_activity_id integer not null,
        vendor_id integer not null,
        created_at timestamp(6),
        end_time timestamp(6) not null,
        start_time timestamp(6) not null,
        updated_at timestamp(6),
        color varchar(255),
        event_title varchar(255) not null,
        primary key (id)
    );

    create table cart (
        id integer generated by default as identity,
        member_id integer,
        product_id integer not null,
        quantity integer not null,
        created_date timestamp(6),
        primary key (id)
    );

    create table certification_tag (
        id integer generated by default as identity,
        keywords varchar(255),
        tag_name varchar(255) not null unique,
        primary key (id)
    );

    create table chat_messages (
        id integer generated by default as identity,
        isRead boolean not null,
        receiver_id integer not null,
        sender_id integer not null,
        send_time timestamp(6),
        content varchar(255) not null,
        primary key (id)
    );

    create table chat_photo (
        chat_messages_id integer not null,
        id integer generated by default as identity,
        photo varchar(255),
        primary key (id)
    );

    create table coupons (
        discount_type boolean not null,
        discount_value numeric(10,0) not null,
        id integer generated by default as identity,
        limit_count integer not null,
        min_order_value numeric(10,0) not null,
        status bit default 0 not null,
        valid_end timestamp(6) not null,
        valid_start timestamp(6) not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table friendly_shop (
        id integer generated by default as identity,
        latitude numeric(38,2),
        longitude numeric(38,2),
        vendor_category_id integer,
        vendor_id integer,
        address varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table member (
        birthdate date,
        gender boolean not null,
        id integer not null,
        status BIT DEFAULT 0 not null,
        updated_date timestamp(6),
        address varchar(255),
        name varchar(255),
        phone varchar(255),
        profile_photo blob,
        primary key (id)
    );

    create table member_coupon (
        coupons_id integer not null,
        member_id integer not null,
        status bit default 1,
        usage_count integer,
        primary key (coupons_id, member_id)
    );

    create table notification (
        id integer generated by default as identity,
        is_read boolean not null,
        member_id integer,
        vendor_activity_id integer,
        vendor_id integer,
        sent_time timestamp(6) not null,
        notification_content varchar(1000) not null,
        notification_title varchar(255) not null,
        primary key (id)
    );

    create table "order" (
        coupon_id integer,
        discount_amount numeric(10,0) not null,
        id integer generated by default as identity,
        member_id integer not null,
        order_status_id integer not null,
        shipping_fee numeric(10,0) not null,
        subtotal numeric(10,0) not null,
        total_amount numeric(10,0) not null,
        created_time timestamp(6) not null,
        updated_date timestamp(6),
        note varchar(255),
        primary key (id)
    );

    create table order_details (
        discount_price numeric(10,0),
        id integer generated by default as identity,
        order_id integer not null,
        product_id integer not null,
        quantity integer not null,
        total_price numeric(10,0) not null,
        unit_price numeric(10,0) not null,
        primary key (id)
    );

    create table order_status (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table payment (
        id integer generated by default as identity,
        order_id integer not null unique,
        payment_amount numeric(10,0) not null,
        payment_category_id integer not null,
        payment_status_id integer not null,
        payment_date timestamp(6) not null,
        updated_date timestamp(6) not null,
        trade_no varchar(255),
        primary key (id)
    );

    create table payment_category (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table payment_status (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product (
        discount_price numeric(10,0),
        id integer generated by default as identity,
        product_color_id integer,
        product_detail_id integer not null,
        product_size_id integer,
        status boolean not null,
        stock_quantity integer not null,
        unit_price numeric(10,0) not null,
        created_time timestamp(6),
        photo blob,
        primary key (id),
        unique (product_detail_id, product_color_id, product_size_id)
    );

    create table product_category (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_color (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_detail (
        id integer generated by default as identity,
        product_category_id integer not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_review (
        id integer generated by default as identity,
        member_id integer not null,
        product_id integer not null,
        rating integer not null,
        review_time timestamp(6),
        review_description varchar(255),
        primary key (id),
        unique (product_id, member_id)
    );

    create table product_review_photo (
        id integer generated by default as identity,
        product_review_id integer not null,
        review_photo blob not null,
        primary key (id)
    );

    create table product_size (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table review_photo (
        id integer generated by default as identity,
        vendor_review_id integer not null,
        photo blob not null,
        primary key (id)
    );

    create table shipping (
        id integer generated by default as identity,
        order_id integer not null unique,
        shipping_address_id integer not null,
        shipping_category_id integer not null,
        shipping_date timestamp(6) not null,
        updated_time timestamp(6) not null,
        receiver_name varchar(255) not null,
        receiver_phone varchar(255) not null,
        primary key (id)
    );

    create table shipping_address (
        id integer generated by default as identity,
        is_current BIT DEFAULT 0 not null,
        member_id integer not null,
        city varchar(255) not null,
        street varchar(255) not null,
        primary key (id)
    );

    create table shipping_category (
        id integer generated by default as identity,
        shipping_cost DECIMAL(10,0) DEFAULT 0 not null,
        shipping_day INT DEFAULT 7 not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        admin_level integer check ((admin_level<=1) and (admin_level>=0)),
        email_verified boolean,
        id integer generated by default as identity,
        is_super_admin boolean,
        local_enabled boolean,
        token_expiry timestamp(6),
        email varchar(255) not null,
        password varchar(255) not null,
        verification_token varchar(255),
        provider enum ('GOOGLE','LOCAL'),
        user_role enum ('ADMIN','MEMBER','VENDOR') not null,
        primary key (id)
    );

    create table vendor (
        avg_rating_environment float(24),
        avg_rating_price float(24),
        avg_rating_service float(24),
        event_count integer,
        id integer not null,
        review_count integer,
        status boolean not null,
        total_rating float(24),
        vendor_category_id integer,
        registration_date timestamp(6),
        updated_date timestamp(6),
        address varchar(255),
        contact_email varchar(255),
        contact_person varchar(255),
        description varchar(255),
        logo_img varbinary(255),
        name varchar(255),
        phone varchar(255),
        taxid_number varchar(255),
        vendor_level varchar(255) not null,
        primary key (id)
    );

    create table vendor_activity (
        activity_type_id integer not null,
        id integer generated by default as identity,
        is_registration_required boolean not null,
        number_visitor integer not null,
        vendor_id integer not null,
        end_time timestamp(6) not null,
        registration_date timestamp(6),
        start_time timestamp(6) not null,
        address varchar(255) not null,
        description varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table vendor_activity_images (
        id integer generated by default as identity,
        vendor_activity_id integer not null,
        image blob not null,
        primary key (id)
    );

    create table vendor_activity_review (
        id integer generated by default as identity,
        member_id integer,
        vendor_activity_id integer not null,
        vendor_id integer not null,
        review_time timestamp(6) not null,
        review_content varchar(255) not null,
        primary key (id)
    );

    create table vendor_category (
        id integer generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table vendor_certification (
        id integer generated by default as identity,
        vendor_id integer not null,
        approved_date timestamp(6),
        request_date timestamp(6),
        reason varchar(1000),
        certification_status NVARCHAR(50) DEFAULT '申請中' not null,
        primary key (id)
    );

    create table vendor_certification_tag (
        certification_id integer not null,
        id integer generated by default as identity,
        meets_standard boolean not null,
        tag_id integer not null,
        vendor_id integer not null,
        primary key (id)
    );

    create table vendor_images (
        id integer generated by default as identity,
        vendor_id integer not null,
        image blob not null,
        primary key (id)
    );

    create table vendor_like (
        id integer generated by default as identity,
        member_id integer,
        vendor_id integer,
        primary key (id)
    );

    create table vendor_review (
        id integer generated by default as identity,
        member_id integer not null,
        rating_environment integer,
        rating_price integer,
        rating_service integer,
        vendor_id integer not null,
        review_time timestamp(6) not null,
        review_content varchar(255),
        primary key (id)
    );

    alter table if exists activity_like 
       add constraint FKpqm80ijk7i1sq98rl7hyb30e3 
       foreign key (member_id) 
       references member;

    alter table if exists activity_like 
       add constraint FKkljpm2l7e6fvac0741v1p3x3f 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists activity_people_number 
       add constraint FKdh7cllsfed811p7wrohr7fxu3 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists activity_registration 
       add constraint FKl0150txbqukiomt4jo9bhq3lt 
       foreign key (member_id) 
       references member;

    alter table if exists activity_registration 
       add constraint FK4peep8xww1qx98bkiotep4mdf 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists admin 
       add constraint FKqer4e53tfnl17s22ior7fcsv8 
       foreign key (id) 
       references users;

    alter table if exists admin_product_reply 
       add constraint FK6h7i4cuq6asgpsteiaxi7p4fr 
       foreign key (admin_id) 
       references admin;

    alter table if exists admin_product_reply 
       add constraint FKfyxyc2vxmps1i7by5dfybut51 
       foreign key (product_review_id) 
       references product_review;

    alter table if exists calendar_event 
       add constraint FKsptdbodpdgjbat34pucrxc20b 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists calendar_event 
       add constraint FK78smuqnpgj00uujvognmjirwq 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists cart 
       add constraint FKix170nytunweovf2v9137mx2o 
       foreign key (member_id) 
       references member;

    alter table if exists cart 
       add constraint FK3d704slv66tw6x5hmbm6p2x3u 
       foreign key (product_id) 
       references product;

    alter table if exists chat_messages 
       add constraint FKand7mh9iu4kt3n1tn2w9i9of0 
       foreign key (receiver_id) 
       references users;

    alter table if exists chat_messages 
       add constraint FKgiqeap8ays4lf684x7m0r2729 
       foreign key (sender_id) 
       references users;

    alter table if exists chat_photo 
       add constraint FK6pu22838suxmuaeqcpplhyh0q 
       foreign key (chat_messages_id) 
       references chat_messages;

    alter table if exists friendly_shop 
       add constraint FK8q79tp71ewdt7trb3v2hsxjnv 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists friendly_shop 
       add constraint FK86a55ixovh0q2hgnkgrpjo8t 
       foreign key (vendor_category_id) 
       references vendor_category;

    alter table if exists member 
       add constraint FKeog0m8jm2ck5j048aeswwrqcv 
       foreign key (id) 
       references users;

    alter table if exists member_coupon 
       add constraint FK56chduq1uvumvj9xv6by7jqrl 
       foreign key (coupons_id) 
       references coupons;

    alter table if exists member_coupon 
       add constraint FKf8n3lu0dfwmhvcikamg220lgg 
       foreign key (member_id) 
       references member;

    alter table if exists notification 
       add constraint FK1xep8o2ge7if6diclyyx53v4q 
       foreign key (member_id) 
       references member;

    alter table if exists notification 
       add constraint FK7usgy1efav68q2dfbjnf7a870 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists notification 
       add constraint FKhfr2sgrl6fhi36elb94vqedft 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists "order" 
       add constraint FKt2l0f3ogjf20tq58glk8t09tr 
       foreign key (coupon_id) 
       references coupons;

    alter table if exists "order" 
       add constraint FKbtfnkke0l8kyq7lyhpwjtg5ev 
       foreign key (member_id) 
       references member;

    alter table if exists "order" 
       add constraint FKcxpcc11kb45j9kjf2qol0pmvm 
       foreign key (order_status_id) 
       references order_status;

    alter table if exists order_details 
       add constraint FK4du41awqfrviisty6wc7caunp 
       foreign key (order_id) 
       references "order";

    alter table if exists order_details 
       add constraint FKinivj2k1370kw224lavkm3rqm 
       foreign key (product_id) 
       references product;

    alter table if exists payment 
       add constraint FK33pd2iqamm9gp5c14r1catra2 
       foreign key (order_id) 
       references "order";

    alter table if exists payment 
       add constraint FKd9y272nk5a74rdtxawxdmqpds 
       foreign key (payment_category_id) 
       references payment_category;

    alter table if exists payment 
       add constraint FKkggljyawkbwc50f0fentflj8t 
       foreign key (payment_status_id) 
       references payment_status;

    alter table if exists product 
       add constraint FKrc2n9xqgygbx2300ka9x1mseb 
       foreign key (product_color_id) 
       references product_color;

    alter table if exists product 
       add constraint FKr9faxumx2401v6n081g0ju9u 
       foreign key (product_detail_id) 
       references product_detail;

    alter table if exists product 
       add constraint FK28qnlp6clpagwv0fqjnqqbtid 
       foreign key (product_size_id) 
       references product_size;

    alter table if exists product_detail 
       add constraint FK27il54tvxjeg6v2wloaobkpv1 
       foreign key (product_category_id) 
       references product_category;

    alter table if exists product_review 
       add constraint FKrgdi6011r51iv9nf26omocl7v 
       foreign key (member_id) 
       references member;

    alter table if exists product_review 
       add constraint FKkaqmhakwt05p3n0px81b9pdya 
       foreign key (product_id) 
       references product;

    alter table if exists product_review_photo 
       add constraint FK8kmfeghxxyk9oomh9y72a7p8k 
       foreign key (product_review_id) 
       references product_review;

    alter table if exists review_photo 
       add constraint FK686r5hsoi21jjgw1ta0ffppwr 
       foreign key (vendor_review_id) 
       references vendor_review;

    alter table if exists shipping 
       add constraint FK1tuspk6hsudt3desli2ty4609 
       foreign key (order_id) 
       references "order";

    alter table if exists shipping 
       add constraint FKjdy5t5asbskyrojgw19vps94q 
       foreign key (shipping_address_id) 
       references shipping_address;

    alter table if exists shipping 
       add constraint FK2y9087ci7maahookairsbkd92 
       foreign key (shipping_category_id) 
       references shipping_category;

    alter table if exists shipping_address 
       add constraint FKmyfu4e8no9xiafndjxjmu8177 
       foreign key (member_id) 
       references member;

    alter table if exists vendor 
       add constraint FKf7029qgg0bcjtf6dbc72embqr 
       foreign key (vendor_category_id) 
       references vendor_category;

    alter table if exists vendor 
       add constraint FK23he99nciwspxtldcr1x7djjk 
       foreign key (id) 
       references users;

    alter table if exists vendor_activity 
       add constraint FKanfvmjq668u9w5of7i4laextn 
       foreign key (activity_type_id) 
       references activity_type;

    alter table if exists vendor_activity 
       add constraint FKlypd3wp8blaqn5vjk2aq06ocf 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_activity_images 
       add constraint FKmq3djj5ygwhtms4805cqbpoqa 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists vendor_activity_review 
       add constraint FK24sn9uaej1vicb1qsll87qsnh 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_activity_review 
       add constraint FKgrykb4d828786x8bwmfe6hofb 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists vendor_certification 
       add constraint FKi7k9wkl7kwycsd1yt4s3uiwvf 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_certification_tag 
       add constraint FKc6o7lxsxelxibd84cct8md7cs 
       foreign key (certification_id) 
       references vendor_certification;

    alter table if exists vendor_certification_tag 
       add constraint FKhwi9r3hvaprsof91bn0rv4k3m 
       foreign key (tag_id) 
       references certification_tag;

    alter table if exists vendor_certification_tag 
       add constraint FKqxdsuf5fnn8qr42r8quee527r 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_images 
       add constraint FKgyn512l9xa4ejyq2vomlj2r7s 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_review 
       add constraint FKmlrsk9erd14566a6kufo343l 
       foreign key (member_id) 
       references member;

    alter table if exists vendor_review 
       add constraint FK6gv7f3skkj0ew5xsrq8sj47hy 
       foreign key (vendor_id) 
       references vendor;

    create table activity_like (
        id integer generated by default as identity,
        member_id integer not null,
        vendor_activity_id integer not null,
        primary key (id)
    );

    create table activity_people_number (
        current_participants integer not null,
        id integer generated by default as identity,
        max_participants integer not null,
        vendor_activity_id integer not null unique,
        primary key (id)
    );

    create table activity_registration (
        id integer generated by default as identity,
        member_id integer not null,
        vendor_activity_id integer not null,
        registration_time timestamp(6) not null,
        status varchar(255) not null,
        primary key (id)
    );

    create table activity_type (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table admin (
        id integer not null,
        registration_date timestamp(6),
        name varchar(255) not null,
        role enum ('ADMIN','EMPLOYEE','SA') not null,
        primary key (id)
    );

    create table admin_product_reply (
        admin_id integer not null,
        id integer generated by default as identity,
        product_review_id integer not null,
        reply_time timestamp(6) not null,
        reply_text varchar(255) not null,
        primary key (id)
    );

    create table calendar_event (
        id integer generated by default as identity,
        vendor_activity_id integer not null,
        vendor_id integer not null,
        created_at timestamp(6),
        end_time timestamp(6) not null,
        start_time timestamp(6) not null,
        updated_at timestamp(6),
        color varchar(255),
        event_title varchar(255) not null,
        primary key (id)
    );

    create table cart (
        id integer generated by default as identity,
        member_id integer,
        product_id integer not null,
        quantity integer not null,
        created_date timestamp(6),
        primary key (id)
    );

    create table certification_tag (
        id integer generated by default as identity,
        keywords varchar(255),
        tag_name varchar(255) not null unique,
        primary key (id)
    );

    create table chat_messages (
        id integer generated by default as identity,
        isRead boolean not null,
        receiver_id integer not null,
        sender_id integer not null,
        send_time timestamp(6),
        content varchar(255) not null,
        primary key (id)
    );

    create table chat_photo (
        chat_messages_id integer not null,
        id integer generated by default as identity,
        photo varchar(255),
        primary key (id)
    );

    create table coupons (
        discount_type boolean not null,
        discount_value numeric(10,0) not null,
        id integer generated by default as identity,
        limit_count integer not null,
        min_order_value numeric(10,0) not null,
        status bit default 0 not null,
        valid_end timestamp(6) not null,
        valid_start timestamp(6) not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table friendly_shop (
        id integer generated by default as identity,
        latitude numeric(38,2),
        longitude numeric(38,2),
        vendor_category_id integer,
        vendor_id integer,
        address varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table member (
        birthdate date,
        gender boolean not null,
        id integer not null,
        status BIT DEFAULT 0 not null,
        updated_date timestamp(6),
        address varchar(255),
        name varchar(255),
        phone varchar(255),
        profile_photo blob,
        primary key (id)
    );

    create table member_coupon (
        coupons_id integer not null,
        member_id integer not null,
        status bit default 1,
        usage_count integer,
        primary key (coupons_id, member_id)
    );

    create table notification (
        id integer generated by default as identity,
        is_read boolean not null,
        member_id integer,
        vendor_activity_id integer,
        vendor_id integer,
        sent_time timestamp(6) not null,
        notification_content varchar(1000) not null,
        notification_title varchar(255) not null,
        primary key (id)
    );

    create table "order" (
        coupon_id integer,
        discount_amount numeric(10,0) not null,
        id integer generated by default as identity,
        member_id integer not null,
        order_status_id integer not null,
        shipping_fee numeric(10,0) not null,
        subtotal numeric(10,0) not null,
        total_amount numeric(10,0) not null,
        created_time timestamp(6) not null,
        updated_date timestamp(6),
        note varchar(255),
        primary key (id)
    );

    create table order_details (
        discount_price numeric(10,0),
        id integer generated by default as identity,
        order_id integer not null,
        product_id integer not null,
        quantity integer not null,
        total_price numeric(10,0) not null,
        unit_price numeric(10,0) not null,
        primary key (id)
    );

    create table order_status (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table payment (
        id integer generated by default as identity,
        order_id integer not null unique,
        payment_amount numeric(10,0) not null,
        payment_category_id integer not null,
        payment_status_id integer not null,
        payment_date timestamp(6) not null,
        updated_date timestamp(6) not null,
        trade_no varchar(255),
        primary key (id)
    );

    create table payment_category (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table payment_status (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product (
        discount_price numeric(10,0),
        id integer generated by default as identity,
        product_color_id integer,
        product_detail_id integer not null,
        product_size_id integer,
        status boolean not null,
        stock_quantity integer not null,
        unit_price numeric(10,0) not null,
        created_time timestamp(6),
        photo blob,
        primary key (id),
        unique (product_detail_id, product_color_id, product_size_id)
    );

    create table product_category (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_color (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_detail (
        id integer generated by default as identity,
        product_category_id integer not null,
        description varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table product_review (
        id integer generated by default as identity,
        member_id integer not null,
        product_id integer not null,
        rating integer not null,
        review_time timestamp(6),
        review_description varchar(255),
        primary key (id),
        unique (product_id, member_id)
    );

    create table product_review_photo (
        id integer generated by default as identity,
        product_review_id integer not null,
        review_photo blob not null,
        primary key (id)
    );

    create table product_size (
        id integer generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table review_photo (
        id integer generated by default as identity,
        vendor_review_id integer not null,
        photo blob not null,
        primary key (id)
    );

    create table shipping (
        id integer generated by default as identity,
        order_id integer not null unique,
        shipping_address_id integer not null,
        shipping_category_id integer not null,
        shipping_date timestamp(6) not null,
        updated_time timestamp(6) not null,
        receiver_name varchar(255) not null,
        receiver_phone varchar(255) not null,
        primary key (id)
    );

    create table shipping_address (
        id integer generated by default as identity,
        is_current BIT DEFAULT 0 not null,
        member_id integer not null,
        city varchar(255) not null,
        street varchar(255) not null,
        primary key (id)
    );

    create table shipping_category (
        id integer generated by default as identity,
        shipping_cost DECIMAL(10,0) DEFAULT 0 not null,
        shipping_day INT DEFAULT 7 not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table users (
        admin_level integer check ((admin_level<=1) and (admin_level>=0)),
        email_verified boolean,
        id integer generated by default as identity,
        is_super_admin boolean,
        local_enabled boolean,
        token_expiry timestamp(6),
        email varchar(255) not null,
        password varchar(255) not null,
        verification_token varchar(255),
        provider enum ('GOOGLE','LOCAL'),
        user_role enum ('ADMIN','MEMBER','VENDOR') not null,
        primary key (id)
    );

    create table vendor (
        avg_rating_environment float(24),
        avg_rating_price float(24),
        avg_rating_service float(24),
        event_count integer,
        id integer not null,
        review_count integer,
        status boolean not null,
        total_rating float(24),
        vendor_category_id integer,
        registration_date timestamp(6),
        updated_date timestamp(6),
        address varchar(255),
        contact_email varchar(255),
        contact_person varchar(255),
        description varchar(255),
        logo_img varbinary(255),
        name varchar(255),
        phone varchar(255),
        taxid_number varchar(255),
        vendor_level varchar(255) not null,
        primary key (id)
    );

    create table vendor_activity (
        activity_type_id integer not null,
        id integer generated by default as identity,
        is_registration_required boolean not null,
        number_visitor integer not null,
        vendor_id integer not null,
        end_time timestamp(6) not null,
        registration_date timestamp(6),
        start_time timestamp(6) not null,
        address varchar(255) not null,
        description varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table vendor_activity_images (
        id integer generated by default as identity,
        vendor_activity_id integer not null,
        image blob not null,
        primary key (id)
    );

    create table vendor_activity_review (
        id integer generated by default as identity,
        member_id integer,
        vendor_activity_id integer not null,
        vendor_id integer not null,
        review_time timestamp(6) not null,
        review_content varchar(255) not null,
        primary key (id)
    );

    create table vendor_category (
        id integer generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table vendor_certification (
        id integer generated by default as identity,
        vendor_id integer not null,
        approved_date timestamp(6),
        request_date timestamp(6),
        reason varchar(1000),
        certification_status NVARCHAR(50) DEFAULT '申請中' not null,
        primary key (id)
    );

    create table vendor_certification_tag (
        certification_id integer not null,
        id integer generated by default as identity,
        meets_standard boolean not null,
        tag_id integer not null,
        vendor_id integer not null,
        primary key (id)
    );

    create table vendor_images (
        id integer generated by default as identity,
        vendor_id integer not null,
        image blob not null,
        primary key (id)
    );

    create table vendor_like (
        id integer generated by default as identity,
        member_id integer,
        vendor_id integer,
        primary key (id)
    );

    create table vendor_review (
        id integer generated by default as identity,
        member_id integer not null,
        rating_environment integer,
        rating_price integer,
        rating_service integer,
        vendor_id integer not null,
        review_time timestamp(6) not null,
        review_content varchar(255),
        primary key (id)
    );

    alter table if exists activity_like 
       add constraint FKpqm80ijk7i1sq98rl7hyb30e3 
       foreign key (member_id) 
       references member;

    alter table if exists activity_like 
       add constraint FKkljpm2l7e6fvac0741v1p3x3f 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists activity_people_number 
       add constraint FKdh7cllsfed811p7wrohr7fxu3 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists activity_registration 
       add constraint FKl0150txbqukiomt4jo9bhq3lt 
       foreign key (member_id) 
       references member;

    alter table if exists activity_registration 
       add constraint FK4peep8xww1qx98bkiotep4mdf 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists admin 
       add constraint FKqer4e53tfnl17s22ior7fcsv8 
       foreign key (id) 
       references users;

    alter table if exists admin_product_reply 
       add constraint FK6h7i4cuq6asgpsteiaxi7p4fr 
       foreign key (admin_id) 
       references admin;

    alter table if exists admin_product_reply 
       add constraint FKfyxyc2vxmps1i7by5dfybut51 
       foreign key (product_review_id) 
       references product_review;

    alter table if exists calendar_event 
       add constraint FKsptdbodpdgjbat34pucrxc20b 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists calendar_event 
       add constraint FK78smuqnpgj00uujvognmjirwq 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists cart 
       add constraint FKix170nytunweovf2v9137mx2o 
       foreign key (member_id) 
       references member;

    alter table if exists cart 
       add constraint FK3d704slv66tw6x5hmbm6p2x3u 
       foreign key (product_id) 
       references product;

    alter table if exists chat_messages 
       add constraint FKand7mh9iu4kt3n1tn2w9i9of0 
       foreign key (receiver_id) 
       references users;

    alter table if exists chat_messages 
       add constraint FKgiqeap8ays4lf684x7m0r2729 
       foreign key (sender_id) 
       references users;

    alter table if exists chat_photo 
       add constraint FK6pu22838suxmuaeqcpplhyh0q 
       foreign key (chat_messages_id) 
       references chat_messages;

    alter table if exists friendly_shop 
       add constraint FK8q79tp71ewdt7trb3v2hsxjnv 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists friendly_shop 
       add constraint FK86a55ixovh0q2hgnkgrpjo8t 
       foreign key (vendor_category_id) 
       references vendor_category;

    alter table if exists member 
       add constraint FKeog0m8jm2ck5j048aeswwrqcv 
       foreign key (id) 
       references users;

    alter table if exists member_coupon 
       add constraint FK56chduq1uvumvj9xv6by7jqrl 
       foreign key (coupons_id) 
       references coupons;

    alter table if exists member_coupon 
       add constraint FKf8n3lu0dfwmhvcikamg220lgg 
       foreign key (member_id) 
       references member;

    alter table if exists notification 
       add constraint FK1xep8o2ge7if6diclyyx53v4q 
       foreign key (member_id) 
       references member;

    alter table if exists notification 
       add constraint FK7usgy1efav68q2dfbjnf7a870 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists notification 
       add constraint FKhfr2sgrl6fhi36elb94vqedft 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists "order" 
       add constraint FKt2l0f3ogjf20tq58glk8t09tr 
       foreign key (coupon_id) 
       references coupons;

    alter table if exists "order" 
       add constraint FKbtfnkke0l8kyq7lyhpwjtg5ev 
       foreign key (member_id) 
       references member;

    alter table if exists "order" 
       add constraint FKcxpcc11kb45j9kjf2qol0pmvm 
       foreign key (order_status_id) 
       references order_status;

    alter table if exists order_details 
       add constraint FK4du41awqfrviisty6wc7caunp 
       foreign key (order_id) 
       references "order";

    alter table if exists order_details 
       add constraint FKinivj2k1370kw224lavkm3rqm 
       foreign key (product_id) 
       references product;

    alter table if exists payment 
       add constraint FK33pd2iqamm9gp5c14r1catra2 
       foreign key (order_id) 
       references "order";

    alter table if exists payment 
       add constraint FKd9y272nk5a74rdtxawxdmqpds 
       foreign key (payment_category_id) 
       references payment_category;

    alter table if exists payment 
       add constraint FKkggljyawkbwc50f0fentflj8t 
       foreign key (payment_status_id) 
       references payment_status;

    alter table if exists product 
       add constraint FKrc2n9xqgygbx2300ka9x1mseb 
       foreign key (product_color_id) 
       references product_color;

    alter table if exists product 
       add constraint FKr9faxumx2401v6n081g0ju9u 
       foreign key (product_detail_id) 
       references product_detail;

    alter table if exists product 
       add constraint FK28qnlp6clpagwv0fqjnqqbtid 
       foreign key (product_size_id) 
       references product_size;

    alter table if exists product_detail 
       add constraint FK27il54tvxjeg6v2wloaobkpv1 
       foreign key (product_category_id) 
       references product_category;

    alter table if exists product_review 
       add constraint FKrgdi6011r51iv9nf26omocl7v 
       foreign key (member_id) 
       references member;

    alter table if exists product_review 
       add constraint FKkaqmhakwt05p3n0px81b9pdya 
       foreign key (product_id) 
       references product;

    alter table if exists product_review_photo 
       add constraint FK8kmfeghxxyk9oomh9y72a7p8k 
       foreign key (product_review_id) 
       references product_review;

    alter table if exists review_photo 
       add constraint FK686r5hsoi21jjgw1ta0ffppwr 
       foreign key (vendor_review_id) 
       references vendor_review;

    alter table if exists shipping 
       add constraint FK1tuspk6hsudt3desli2ty4609 
       foreign key (order_id) 
       references "order";

    alter table if exists shipping 
       add constraint FKjdy5t5asbskyrojgw19vps94q 
       foreign key (shipping_address_id) 
       references shipping_address;

    alter table if exists shipping 
       add constraint FK2y9087ci7maahookairsbkd92 
       foreign key (shipping_category_id) 
       references shipping_category;

    alter table if exists shipping_address 
       add constraint FKmyfu4e8no9xiafndjxjmu8177 
       foreign key (member_id) 
       references member;

    alter table if exists vendor 
       add constraint FKf7029qgg0bcjtf6dbc72embqr 
       foreign key (vendor_category_id) 
       references vendor_category;

    alter table if exists vendor 
       add constraint FK23he99nciwspxtldcr1x7djjk 
       foreign key (id) 
       references users;

    alter table if exists vendor_activity 
       add constraint FKanfvmjq668u9w5of7i4laextn 
       foreign key (activity_type_id) 
       references activity_type;

    alter table if exists vendor_activity 
       add constraint FKlypd3wp8blaqn5vjk2aq06ocf 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_activity_images 
       add constraint FKmq3djj5ygwhtms4805cqbpoqa 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists vendor_activity_review 
       add constraint FK24sn9uaej1vicb1qsll87qsnh 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_activity_review 
       add constraint FKgrykb4d828786x8bwmfe6hofb 
       foreign key (vendor_activity_id) 
       references vendor_activity;

    alter table if exists vendor_certification 
       add constraint FKi7k9wkl7kwycsd1yt4s3uiwvf 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_certification_tag 
       add constraint FKc6o7lxsxelxibd84cct8md7cs 
       foreign key (certification_id) 
       references vendor_certification;

    alter table if exists vendor_certification_tag 
       add constraint FKhwi9r3hvaprsof91bn0rv4k3m 
       foreign key (tag_id) 
       references certification_tag;

    alter table if exists vendor_certification_tag 
       add constraint FKqxdsuf5fnn8qr42r8quee527r 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_images 
       add constraint FKgyn512l9xa4ejyq2vomlj2r7s 
       foreign key (vendor_id) 
       references vendor;

    alter table if exists vendor_review 
       add constraint FKmlrsk9erd14566a6kufo343l 
       foreign key (member_id) 
       references member;

    alter table if exists vendor_review 
       add constraint FK6gv7f3skkj0ew5xsrq8sj47hy 
       foreign key (vendor_id) 
       references vendor;
